### ISSUE TITLE
Update to 1.19.3 Please

### ISSUE THREAD

**Issue by sternschnaube** [RacoonDog/Anvil-Display#3]
java.lang.NoSuchFieldError: field_11160
	at Not Enough Crashes deobfuscated stack trace.(1.19.3+build.4)
	at io.github.racoondog.anvildisplay.Util.getBaseCost(Util.java:36)
	at net.minecraft.item.ItemStack.handler$zzn000$onGetTooltip(ItemStack:2158)
	at net.minecraft.item.ItemStack.getTooltip(ItemStack:828)
	at net.minecraft.client.MinecraftClient.method_1485(MinecraftClient:818)
	at net.minecraft.client.search.TextSearcher.of(TextSearcher:20)
	at net.minecraft.client.search.TextSearchProvider.reload(TextSearchProvider:26)
	at net.minecraft.client.search.SearchManager$Instance.reload(SearchManager:61)
	at net.minecraft.client.search.SearchManager.reload(SearchManager:42)
	at net.minecraft.client.MinecraftClient.reloadSearchProvider(MinecraftClient:2636)
	at net.minecraft.client.MinecraftClient.method_46740(MinecraftClient:836)
	at net.minecraft.item.ItemGroup.reloadSearchProvider(ItemGroup:119)
	at net.minecraft.item.ItemGroup.updateEntries(ItemGroup:98)
	at net.minecraft.item.ItemGroups.method_47331(ItemGroups:1920)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at net.minecraft.item.ItemGroups.updateEntries(ItemGroups:1920)
	at net.minecraft.item.ItemGroups.updateDisplayParameters(ItemGroups:1934)
	at de.siphalor.mousewheelie.client.util.CreativeSearchOrder.refreshItemSearchPositionLookup(CreativeSearchOrder.java:65)
	at de.siphalor.mousewheelie.client.MWClient.lambda$onInitializeClient$1(MWClient.java:97)
	at net.fabricmc.fabric.api.client.networking.v1.ClientPlayConnectionEvents.lambda$static$2(ClientPlayConnectionEvents.java:50)
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.onServerReady(ClientPlayNetworkAddon.java:70)
	at net.minecraft.client.network.ClientPlayNetworkHandler.handler$eki000$handleServerPlayReady(ClientPlayNetworkHandler:4146)
	at net.minecraft.client.network.ClientPlayNetworkHandler.onGameJoin(ClientPlayNetworkHandler:448)
	at net.minecraft.network.packet.s2c.play.GameJoinS2CPacket.apply(GameJoinS2CPacket:87)
	at net.minecraft.network.packet.s2c.play.GameJoinS2CPacket.apply(GameJoinS2CPacket:21)
	at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils:22)
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:156)
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23)
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:130)
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:115)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1144)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:781)
	at net.minecraft.client.main.Main.main(Main:244)
	at net.minecraft.client.main.Main.main(Main:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by venaminecraft** [comment]
Thank you 🥳
